// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz8S3aj5f2l-qS5QfhUPheiLreHgYZET0',
    appId: '1:709635274768:web:7be47a9ae56d0c58c9f295',
    messagingSenderId: '709635274768',
    projectId: 'home-exp-manager',
    authDomain: 'home-exp-manager.firebaseapp.com',
    storageBucket: 'home-exp-manager.firebasestorage.app',
    measurementId: 'G-CV70TKW3H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvXq_Ey7UQQFLmfOT6hfa9tsVpsyfTEM8',
    appId: '1:709635274768:android:94ba5d3c72165391c9f295',
    messagingSenderId: '709635274768',
    projectId: 'home-exp-manager',
    storageBucket: 'home-exp-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2KPcYAHpg9ebTASibqQBwGZ6UMRmGCzU',
    appId: '1:709635274768:ios:e0f9b34e819955e2c9f295',
    messagingSenderId: '709635274768',
    projectId: 'home-exp-manager',
    storageBucket: 'home-exp-manager.firebasestorage.app',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2KPcYAHpg9ebTASibqQBwGZ6UMRmGCzU',
    appId: '1:709635274768:ios:e0f9b34e819955e2c9f295',
    messagingSenderId: '709635274768',
    projectId: 'home-exp-manager',
    storageBucket: 'home-exp-manager.firebasestorage.app',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz8S3aj5f2l-qS5QfhUPheiLreHgYZET0',
    appId: '1:709635274768:web:89fa603986186946c9f295',
    messagingSenderId: '709635274768',
    projectId: 'home-exp-manager',
    authDomain: 'home-exp-manager.firebaseapp.com',
    storageBucket: 'home-exp-manager.firebasestorage.app',
    measurementId: 'G-1DTB3F82DK',
  );

}