// File generated by Antigravity based on user-provided config.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu7bhHAYc5PBMXj1hHRkaVNA5N40EMeqE',
    appId: '1:877934920921:web:4e079f47d8d94d3f82aac8',
    messagingSenderId: '877934920921',
    projectId: 'shukla-exp-manager',
    authDomain: 'shukla-exp-manager.firebaseapp.com',
    storageBucket: 'shukla-exp-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4AshyOE1VvfhcvSJEKC89GUN3M5QOu1Y',
    appId: '1:877934920921:android:e770d3aaab5b45d482aac8',
    messagingSenderId: '877934920921',
    projectId: 'shukla-exp-manager',
    storageBucket: 'shukla-exp-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Ehze7ix0NvZ4wJ4H-KupKSwIn_kY6ak',
    appId: '1:877934920921:ios:1cb80e861866a63b82aac8',
    messagingSenderId: '877934920921',
    projectId: 'shukla-exp-manager',
    storageBucket: 'shukla-exp-manager.firebasestorage.app',
    iosBundleId: 'shukla-exp.manager',
  );
}
